#!/bin/bash
make clean
make
sudo rmmod phase2module
sudo insmod phase2module.ko
gcc userland/phase2test.c -o userland/phase2test
echo ===========
echo    USER
echo ===========
userland/phase2test
sleep 4
echo ===========
echo    KERNEL
echo ===========
cat /var/log/syslog | grep P2M | tail -n 10
