#!/bin/bash
cd userland
make clean
make
cd ../kernelland
make clean
make
cd ..
sudo rmmod phase2module
sudo insmod kernelland/phase2module.ko
echo ===========
echo    USER
echo ===========
userland/phase2test
sleep 4
echo ===========
echo    KERNEL
echo ===========
cat /var/log/syslog | grep P2M | tail -n 10
